### PR TITLE
Add first_name and last_name

### PR DESCRIPTION
**Pull request by attiyaIshaque**
### Description
In this PR I have updated the first name and last name of the user and return in also thread data which currently returns user data contains only id and username.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @attiyaIshaque! I've created [OSPR-3672](https://openedx.atlassian.net/browse/OSPR-3672) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by attiyaIshaque** [comment]
@shafqatfarhan can you please review it also https://github.com/edx-solutions/edx-platform/pull/1508?

**Comment by attiyaIshaque** [comment]
@shafqatfarhan yup we will update the first_name and last_name with the managment command.

**Comment by wajeeha-khalid** [comment]
@ihtram Should I merge this? this is urgent client need, would like to get this going.

**Comment by ihtram** [comment]
@wajeeha-khalid  Please go ahead and merge it. The only concern was to write a management command which seems to be written already.

**Pull request merged**
